config/routes.rb
Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationshops, only: [:create, :destroy]
    get 'followings' => 'relationshops#followings', as: 'followings'
    get 'followers' => 'relationshops#followers', as: 'followers'
  end
  
  get '/search' => 'searches#search'
  
  get 'chats/:id' => 'chats#show', as: 'chat'
  post 'chats/:id' => 'chats#create', as: 'new_chat'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # has_many :user
  belongs_to :user
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :chat_room_users, dependent: :destroy
  has_many :users, through: :chat_room_users
  has_many :messages, dependent: :destroy
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat_room
  belongs_to :user
  
  validates :content, presence: true, length: {maximum: 140}
end

app/models/relationshop.rb
class Relationshop < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # belongs_to :books
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :book_comments, dependent: :destroy
  
  # フォローした、されたの関係
  has_many :relationshops, class_name: "Relationshop", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationshops, class_name: "Relationshop", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面で使う
  has_many :followings, through: :relationshops, source: :followed
  has_many :followers, through: :reverse_of_relationshops, source: :follower
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50}

  has_many :chat_room_users, dependent: :destroy
  has_many :chat_rooms, through: :chat_room_users
  has_many :messages, dependent: :destroy
  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def follow(user_id)
    relationshops.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationshops.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @book = Book.find(params[:id])
    @book.increment!(:views_count)
    @new_book = Book.new
    @book_comment = BookComment.new
    @book_comments = BookComment.where(book_id: @book.id)
  end

  def index
    # @books = Book.all
    @books = Book.left_joins(:favorites)
                 .group(:id)
                 .select('books.*, COUNT(favorites.id) AS favorites_count')
                 .order('favorites_count DESC')
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    @user = Book.find(params[:id]).user
    unless @user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @other_user = User.find(params[:id])
    
    chat_room = ChatRoom.joins(:chat_room_users)
                        .where(chat_room_users: { user_id: [current_user.id, @other_user.id] })
                        .group('chat_rooms.id')
                        .having('COUNT(chat_rooms.id) = 2')
                        .first
                        
    if chat_room.nil?
      chat_room = ChatRoom.create
      ChatRoomUser.create(chat_room: chat_room, user: current_user)
      ChatRoomUser.create(chat_room: chat_room, user: @other_user)
    end
    
    @messages = chat_room.messages
    @message = Message.new
    
  end
  
  def create
    @other_user = User.find(params[:id])
    
    chat_room = ChatRoom.joins(:chat_room_users)
                        .where(chat_room_users: { user_id: [current_user.id, @other_user.id] })
                        .group('chat_rooms.id')
                        .having('COUNT(chat_rooms.id) = 2')
                        .first
    
    @message = chat_room.messages.build(message_params)
    @message.user = current_user
    @message.save
    redirect_to chat_path(@other_user)
  end
  
  private
  
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    if params[:category] == "User"
      redirect_to request.referer
    else
      @keyword = params[:title]
      if params[:search_type] == "完全一致"
        @books = Book.where(title: params[:title])
      elsif params[:search_type] == "前方一致"
        @books = Book.where("title LIKE ?", params[:title]+"%")
      elsif params[:search_type] == "後方一致"
        @books = Book.where("title LIKE ?", "%"+params[:title])
      else
        @books = Book.where("title LIKE ?", "%"+params[:title]+"%")
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = current_user
  end

  def update
    if @user.update(user_params)
      # redirect_to users_path(@user), notice: "You have updated user successfully."
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      # render "show"
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each_with_index do |book, i| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td class="favorite-btn">
          <% if book.favorited_by?(current_user) %>
            <%= render 'favorites/favorites_on', book: book, idx: i %>
          <% else %>
            <%= render 'favorites/favorites_off', book: book, idx: i %>
          <% end %>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
        <td>閲覧数：<%= book.views_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          
          <td class="favorite-btn">
            <% if @book.favorited_by?(current_user) %>
              <%= render 'favorites/favorites_on', book: @book, idx: 0 %>
            <% else %>
              <%= render 'favorites/favorites_off', book: @book, idx: 0 %>
            <% end %>
          </td>
          
          <td>コメント数：<%= @book.book_comments.count %></td>
          
          <td>閲覧数：<%= @book.views_count %></td>
          
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      
      <table class='table'>
        <% @book_comments.each do |comment| %>
  		  <tr>
          <td>
              <%= link_to(comment.user) do %>
                <%= image_tag comment.user.get_profile_image, size:"100x100" %><br>
                <%= comment.user.name %>
              <% end %>
          </td>
          <td><%= comment.comment %></td>
          <td>
            <%= link_to 'Destroy', book_book_comment_path(comment), method: :delete, class: "btn btn-sm btn-danger"%>
          </td>
        </tr>
        <% end %>
      </table>
      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <%= f.text_area :comment %>
        <%= f.submit "送信" %>
      <% end %>
      
      
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%=  user.followers.count %></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationshops_path(user.id), method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationshops_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th>
	    <%= link_to user_followings_path(user) do %>
	      <%= user.followings.count %>
	    <% end %>
	  </th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th>
	    <%= link_to user_followers_path(user) do %>
	      <%= user.followers.count %>
	    <% end %>
	  </th>
  </tr>
</table>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= form_with(url: search_path, method: :get, local: true) do |f| %>
  <%= f.text_field :title, class: 'form-control', placeholder: '検索ワード' %>
  <%= f.select :category, [["User", "User"], ["Book", "Book"]] %>
  <%= f.select :search_type, [["完全一致","完全一致"],["前方一致","前方一致"],["後方一致","後方一致"],["部分一致","部分一致"]] %>
  <%= f.submit "検索" %>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <% if current_user.following?(@user) %>
        <%= link_to "フォロー外す", user_relationshops_path(@user.id), method: :delete, class: "btn btn-sm btn-success" %>
        <% if @user.following?(current_user) %>
          <%= link_to "chatを始める", chat_path(@user.id) %>
        <% end %>
      <% else %>
        <%= link_to "フォローする", user_relationshops_path(@user.id), method: :post, class: "btn btn-sm btn-success" %>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>